create view v_otpAdd_full as SELECT 
       [v_geo].*, 
       [main].[tblOtpAdd].[otp_id], 
       [main].[tblOtpAdd].[client_id], 
       [main].[tblOtpAdd].[site_village], 
       [main].[tblOtpAdd].[site_id] AS [site_id1], 
       [main].[tblOtpAdd].[reg_date], 
       [main].[tblOtpAdd].[reg_id], 
       [main].[tblOtpAdd].[p_name], 
       [main].[tblOtpAdd].[f_or_h_name], 
       [main].[tblOtpAdd].[cnic], 
       [main].[tblOtpAdd].[address], 
       [main].[tblOtpAdd].[cnt_number], 
       [main].[tblOtpAdd].[age], 
       [main].[tblOtpAdd].[gender], 
       [main].[tblOtpAdd].[plw_type], 
       [main].[tblOtpAdd].[ent_reason], 
       [main].[tblOtpAdd].[ref_type], 
       [main].[tblOtpAdd].[oedema], 
       [main].[tblOtpAdd].[muac], 
       [main].[tblOtpAdd].[diarrhoea], 
       [main].[tblOtpAdd].[vomiting], 
       [main].[tblOtpAdd].[cough], 
       [main].[tblOtpAdd].[appetite], 
       [main].[tblOtpAdd].[daily_stool], 
       [main].[tblOtpAdd].[pass_urine], 
       [main].[tblOtpAdd].[b_Feeding], 
       [main].[tblOtpAdd].[od_swol_time], 
       [main].[tblOtpAdd].[weight], 
       [main].[tblOtpAdd].[ration1], 
       [main].[tblOtpAdd].[quantity1], 
       [main].[tblOtpAdd].[ration2], 
       [main].[tblOtpAdd].[quantity2], 
       [main].[tblOtpAdd].[ration3], 
       [main].[tblOtpAdd].[quantity3], 
       [main].[tblOtpAdd].[prog_type], 
       [main].[tblOtpAdd].[created_at], 
       [main].[tblOtpAdd].[updated_at]
FROM   [main].[v_geo]
       INNER JOIN [main].[tblOtpAdd] ON [main].[tblOtpAdd].[site_id] = [main].[v_geo].[site_id];

